on:
  push
jobs:
  check-commit-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dguo/check-author-and-committer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          committer-auth-regex: '@example\.com$'
